[project]
name = "yeunrlsd"
version = "0.0.1"
description = "[ye] [unreleased] [music]"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["flask==3.1.2", "flask-cors==6.0.1", "flask-squeeze==3.5.0"]
